environment:

  matrix:
    - PYTHON: "C:\Python35-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build: off

test_script:
  - "%PYTHON%\\python.exe -m unittest discover ./tests"